# Upload package to pypi everytime a release is created
name: Upload release to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Build documentation
        run: |
          cd docs
          uv run make html
          touch _build/html/.nojekyll
          cd ..
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
          CLEAN: true
      - name: Build and publish
        run: |
          uv build
          uv publish --username __token__ --password ${{ secrets.TOKEN_PYPI }}
